name: node deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: inventory-build
          path: dist/
  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: inventory-build
          path: dist/

      - name: File check
        if: ${{ success() }}
        run: ls -la dist/

      - name: If failure
        if: ${{ failure() }}
        run: echo "An earlier step in the deploy job failed.""